version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/volumes/mysql:/var/lib/mysql"
  redis:
      image: redis:2.8
      ports:
        - "6379:6379"
  php:
    image: webdevops/php-dev:7.2
    container_name: mongodb-php
    volumes:
      - "./:/app"
      - "~/.composer:/root/.composer"
    working_dir: '/app'
    ports:
      - "8000:8000"
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/app"
    ports:
      - "80:80"
  mongodb:
      image: 'bitnami/mongodb:latest'
      ports:
        - "27017:27017"
      volumes:
        - "./docker/volumes/mongo:/var/lib/mysql"
